### ISSUE TITLE
Hardcoded path 

### ISSUE THREAD

**Issue by amannain1** [Go-ERP/Ax2Git#8] opened 2016-05-10 12:43 UTC
My Git was installed in Program files so I had to change the path of Git exe to @'C:\Program Files\Git\bin\git.exe'

Maybe it makes sense to have it as a parameter

**Comment by ksix** [comment] 2017-03-17 03:41
It should just use git from the env path, not using a git.exe location.

**Comment by ksix** [comment] 2017-03-17 03:44
This is a duplicate of issue #3 . Should be closed.

**Closed** 2019-09-05 12:17 UTC
